name: Github Actions Demo
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: NPM install
        run: npm install
      - name: Run build
        run: echo "If I was using typescript, this is where I would run `tsc` !"
      - name: Run tests
        run: echo "this is where the tests would run!"
      - name: Complain
        run: echo "uuugh CICD is booring!"
